openapi: 3.1.0
info:
  title: Task management
  description: API for the task management
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array

    post:
      summary: create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: array

    delete:
      summary: delete tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer

      responses:
        '200':
          description: task deleted successfully
          content:
            application/json:
              schema:
                type: array


  /tasks/{id}:
    get:
      summary: get task by its id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: task found
          content:
            application/json:

        '404':
          description: task not found
          content:
            text/plain:
              type: string
              example: "Sorry, task not found"

    delete:
      summary: delete a task by its id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: task deleted successfully
          content:
            application/json:


components:
  schemas:
    task:
      type: object
      properties:
        id:
          type: integer
          example: 1

        title:
          type: string
          example: "test"

        completed:
          type: boolean
          example: false

        taskInput:
          type: object
          properties:
            title:
              type: string
              example: "test"
            completed:
              type: boolean
              example: false
